export const GET_FILE="GET_FILE"
export const GET_FILE_TO_REDUX= "GET_FILE_TO_REDUX"
export const GET_FILE_FROM_POST="GET_FILE_FROM_POST"
export const GET_FILE_FROM_POST_TO_REDUX="GET_FILE_FROM_POST_TO_REDUX"
export const GET_COMMENT="GET_COMMENT"
export const GET_SEARCH_FILE="GET_SEARCH_FILE"

//chat
export const SET_CHAT="SET_CHAT"
export const GET_POST_BY_AMOUNT ="GET_POST_BY_AMOUNT"
export const GET_POST_BY_AMOUNT_TO_REDUX="GET_POST_BY_AMOUNT_TO_REDUX"
